version: '3.9'

services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db-nttdata
    restart: always
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d banco_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - my_postgres_nttdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - microservice-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_new
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
      - "15692:15692"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservice-net
  msvc-customer-person:
    build: ./msvc-customer-person
    container_name: msvc-customer-person-nttdata
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-nttdata:5432/banco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    logging:
      driver: "json-file"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - microservice-net

  msvc-account-movement:
    build: ./msvc-account-movement
    container_name: msvc-account-movement-nttdata
    restart: always
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-nttdata:5432/banco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    logging:
      driver: "json-file"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - microservice-net

volumes:
  my_postgres_nttdata:

networks:
  microservice-net:
    driver: bridge
